# - Try to find the ITL
# Once done this will define
#
#  ITL_FOUND - system has ITL
#  ITL_INCLUDE_DIR - the ITL include directory
#  ITL_LIBRARY


FIND_PATH(ITL_INCLUDE_DIR NAMES prayer.h PATH_SUFFIXES itl)

FIND_LIBRARY(ITL_LIBRARY NAMES itl)

IF (ITL_INCLUDE_DIR AND ITL_LIBRARY)
  SET(ITL_FOUND TRUE)
ENDIF (ITL_INCLUDE_DIR AND ITL_LIBRARY)


IF (ITL_FOUND)
  IF (NOT ITL_FIND_QUIETLY)
    MESSAGE(STATUS "Found ITL: ${ITL_LIBRARY}")
  ENDIF (NOT ITL_FIND_QUIETLY)
ELSE (ITL_FOUND)
  IF (ITL_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find Islamic Tools and Libraries (ITL) <http://www.arabeyes.org/project.php?proj=ITL>")
  ENDIF (ITL_FIND_REQUIRED)
ENDIF (ITL_FOUND)
