
FIND_PATH(ITL_INCLUDE_DIR prayer.h /usr/include/itl /usr/local/include/itl)

FIND_LIBRARY(ITL_LIBRARY NAMES itl PATH /usr/lib /usr/local/lib) 

IF (ITL_INCLUDE_DIR AND ITL_LIBRARY)
   SET(ITL_FOUND TRUE)
ENDIF (ITL_INCLUDE_DIR AND ITL_LIBRARY)


IF (ITL_FOUND)
   IF (NOT ITL_FIND_QUIETLY)
      MESSAGE(STATUS "Found ITL: ${ITL_LIBRARY}")
   ENDIF (NOT ITL_FIND_QUIETLY)
ELSE (ITL_FOUND)
   IF (ITL_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find ITL")
   ENDIF (ITL_FIND_REQUIRED)
ENDIF (ITL_FOUND)
